language: node_js
node_js:
  - "8"
dist: xenial
sudo: false

cache:
  directories:
    - node_modules

addons:
  chrome: stable

script:
  - ng lint
  - ng test --browsers ChromeHeadless --watch false
  - ng build --prod
